dist: bionic
language: c
sudo: require
script:
    - make
    - ./test.sh
addons:
    apt:
        update: true
        packages:
            - libwegkit2gtk-4.0-dev
            - libgtk-3-dev
            - xvfb
            - metacity
            - x11-apps # → xwd
            - imagemagick # → convert
