language: c
sudo: require
install:
    - sudo add-apt-repository -y ppa:webkit-team/ppa
    - sudo apt-get update
    - sudo apt-get install -y libgtk-3-dev
    - sudo apt-get install -y libwebkit2gtk-4.0-dev
    - sudo apt-get install -y xvfb
    - sudo apt-get install -y metacity
    - sudo apt-get install -y x11-apps
    - sudo apt-get install -y imagemagick
script:
    - make
    - ./test.sh
