language: c
sudo: require
install:
    - sudo apt-get update
    - sudo apt-get install -y libgtk-3-dev
    - sudo apt-get install -y libwebkitgtk-dev
    - sudo apt-get install -y xvfb
    - sudo apt-get install -y metacity
    - sudo apt-get install -y x11-apps
    - sudo apt-get install -y imagemagick
script:
    - make
    - ./test.sh
