dist: bionic
language: c
script:
    - make
    - ./test.sh
addons:
    apt:
        update: true
        packages:
            # For build
            - libwebkit2gtk-4.0-dev
            - libgtk-3-dev
            # For testing
            - xvfb
            - compton
            - hsetroot
            - x11-apps # → xwd
            - imagemagick # → convert
